# Generated by Django 2.0.2 on 2018-02-14 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'mp_music',
            },
        ),
        migrations.CreateModel(
            name='PlayListType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'mp_playlist_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'mp_user',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('user', models.ManyToManyField(to='mp_app.User')),
            ],
            options={
                'db_table': 'mp_user_group',
            },
        ),
        migrations.CreateModel(
            name='UserPlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('playlist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.PlayListType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.User')),
            ],
            options={
                'db_table': 'mp_user_playlist',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.User'),
        ),
    ]
